name: Build and Deploy Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-deploy-docs:
    if: ${{ github.event.pull_request.merged }} or ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
